version: "3"
services:
  app:
    build:
      dockerfile: conf/app/Dockerfile
      context: .
    volumes:
      - "./:/usr/app"
    command: "sh ./start.sh"
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build: conf/nginx
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app
